// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UserForm.DAL.Models;

public partial class Campus
{
    public Guid CampusId { get; set; }

    public string CampusCode { get; set; }

    public string CampusName { get; set; }

    public virtual ICollection<FormRegisterService> FormRegisterServices { get; set; } = new List<FormRegisterService>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}