// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UserForm.DAL.Models;

public partial class FormStatus
{
    public int FormStatusId { get; set; }

    public string StatusCode { get; set; }

    public string StatusName { get; set; }

    public virtual ICollection<FormRegisterService> FormRegisterServices { get; set; } = new List<FormRegisterService>();

    public virtual ICollection<FormStatusHistory> FormStatusHistoryFromStatuses { get; set; } = new List<FormStatusHistory>();

    public virtual ICollection<FormStatusHistory> FormStatusHistoryToStatuses { get; set; } = new List<FormStatusHistory>();
}