// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UserForm.DAL.Models;

public partial class FormStatusHistory
{
    public long HistoryId { get; set; }

    public Guid FormId { get; set; }

    public int? FromStatusId { get; set; }

    public int ToStatusId { get; set; }

    public Guid ChangedByUserId { get; set; }

    public DateTime ChangedAt { get; set; }

    public string ChangeNote { get; set; }

    public virtual User ChangedByUser { get; set; }

    public virtual FormRegisterService Form { get; set; }

    public virtual FormStatus FromStatus { get; set; }

    public virtual FormStatus ToStatus { get; set; }
}