// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UserForm.DAL.Models;

public partial class FormRegisterService
{
    public Guid FormId { get; set; }

    public Guid UserId { get; set; }

    public string CourseCode { get; set; }

    public string SupportCode { get; set; }

    public Guid CampusId { get; set; }

    public DateTime? ExamDate { get; set; }

    public Guid ServiceId { get; set; }

    public int FormStatusId { get; set; }

    public Guid? OriginalFormId { get; set; }

    public string Notes { get; set; }

    public string AdminNotes { get; set; }

    public DateTime SubmittedAt { get; set; }

    public DateTime? ApprovedAt { get; set; }

    public Guid? ApprovedByUserId { get; set; }

    public DateTime? RejectedAt { get; set; }

    public Guid? RejectedByUserId { get; set; }

    public virtual User ApprovedByUser { get; set; }

    public virtual Campus Campus { get; set; }

    public virtual FormStatus FormStatus { get; set; }

    public virtual ICollection<FormStatusHistory> FormStatusHistories { get; set; } = new List<FormStatusHistory>();

    public virtual ICollection<FormRegisterService> InverseOriginalForm { get; set; } = new List<FormRegisterService>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual FormRegisterService OriginalForm { get; set; }

    public virtual User RejectedByUser { get; set; }

    public virtual Service Service { get; set; }

    public virtual ICollection<SupportSession> SupportSessions { get; set; } = new List<SupportSession>();

    public virtual User User { get; set; }
}