// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UserForm.DAL.Models;

public partial class Invoice
{
    public Guid InvoiceId { get; set; }

    public Guid FormId { get; set; }

    public Guid UserId { get; set; }

    public int PaymentStatusId { get; set; }

    public decimal Subtotal { get; set; }

    public decimal DiscountAmount { get; set; }

    public decimal? TotalAmount { get; set; }

    public string Currency { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? PaidAt { get; set; }

    public string PaymentRef { get; set; }

    public virtual FormRegisterService Form { get; set; }

    public virtual ICollection<InvoiceItem> InvoiceItems { get; set; } = new List<InvoiceItem>();

    public virtual PaymentStatus PaymentStatus { get; set; }

    public virtual User User { get; set; }
}