// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UserForm.DAL.Models;

public partial class InvoiceItem
{
    public long InvoiceItemId { get; set; }

    public Guid InvoiceId { get; set; }

    public Guid? ServiceId { get; set; }

    public string Description { get; set; }

    public int Qty { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal? LineTotal { get; set; }

    public virtual Invoice Invoice { get; set; }

    public virtual Service Service { get; set; }
}