// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UserForm.DAL.Models;

public partial class Notification
{
    public Guid NotificationId { get; set; }

    public int NotificationTypeId { get; set; }

    public Guid ToUserId { get; set; }

    public Guid? FormId { get; set; }

    public string Subject { get; set; }

    public string Body { get; set; }

    public DateTime SentAt { get; set; }

    public string DeliveryChannel { get; set; }

    public virtual FormRegisterService Form { get; set; }

    public virtual NotificationType NotificationType { get; set; }

    public virtual User ToUser { get; set; }
}