// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UserForm.DAL.Models;

public partial class Service
{
    public Guid ServiceId { get; set; }

    public string ServiceCode { get; set; }

    public string ServiceName { get; set; }

    public decimal ServicePrice { get; set; }

    public virtual ICollection<FormRegisterService> FormRegisterServices { get; set; } = new List<FormRegisterService>();

    public virtual ICollection<InvoiceItem> InvoiceItems { get; set; } = new List<InvoiceItem>();
}