// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UserForm.DAL.Models;

public partial class SupportSession
{
    public Guid SupportSessionId { get; set; }

    public Guid FormId { get; set; }

    public Guid AdminUserId { get; set; }

    public DateTime StartedAt { get; set; }

    public DateTime? EndedAt { get; set; }

    public string OutcomeCode { get; set; }

    public string OutcomeNote { get; set; }

    public virtual User AdminUser { get; set; }

    public virtual FormRegisterService Form { get; set; }
}