// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace UserForm.DAL.Models;

public partial class User
{
    public Guid UserId { get; set; }

    public string StudentId { get; set; }

    public string StudentName { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public bool IsActive { get; set; }

    public Guid? CampusId { get; set; }

    public int RoleId { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public DateTime? LastLoginAt { get; set; }

    public virtual Campus Campus { get; set; }

    public virtual ICollection<FormRegisterService> FormRegisterServiceApprovedByUsers { get; set; } = new List<FormRegisterService>();

    public virtual ICollection<FormRegisterService> FormRegisterServiceRejectedByUsers { get; set; } = new List<FormRegisterService>();

    public virtual ICollection<FormRegisterService> FormRegisterServiceUsers { get; set; } = new List<FormRegisterService>();

    public virtual ICollection<FormStatusHistory> FormStatusHistories { get; set; } = new List<FormStatusHistory>();

    public virtual ICollection<Invoice> Invoices { get; set; } = new List<Invoice>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual Role Role { get; set; }

    public virtual ICollection<SupportSession> SupportSessions { get; set; } = new List<SupportSession>();
}